apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devskin-kubernetes-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "devskin-kubernetes-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  api-key: {{ .Values.apiKey | quote }}
  server-url: {{ .Values.serverUrl | quote }}
